server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/cake_factory_db
    username: cake_user
    password: cake
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: "my-super-secret-key-my-super-secret-key-123456"
  expiration: 3600000